#!/usr/bin/env python3
# nsndswap/viko_nsnd.py
# copyright 2017 ViKomprenas, 2-clause BSD license (LICENSE.md)

from nsndswap.util import Track

nsnd = {
    # A Shade of Two
    "criticalErr0r": ["Taureg"],
    "Exploreation": ["Explore", "Upward Movement (Dave Owns)"],
    "Taureg": ["Sburban Jungle", "Beatdown"],
    "HammertimeVsThatBlackDoggo": ["Beatdown", "Doctor", "Sburban Jungle", "Liquid Negrocity", "BeatVale", "Penumbra Phantasm"],
    "Saviour of the Dancing Demon": ["Doctor", "Penumbra Phantasm", "Beatdown", "Sburban Jungle"],
    "Player 2": ["Sburban Jungle", "Beatdown", "Liquid Negrocity", "Doctor", "Dance of Thorns"],
    "Cascadium Dioxide": ["Cascade (Beta)", "Flare", "Doctor", "Penumbra Phantasm", "Black Rose / Green Sun", "Black Hole / Green Sun", "Sburban Jungle"],
    "Unnamed Jungle Club Remix (Extra)": ["Sburban Jungle"],
    "Tales of an Unknown Universe": [],

    # M3l0m4ni4c soundcloud
    "At Shadow's Edge": ["Penumbra Phantasm", "Amen, Brother"],
    "Whirlwind (L8 for D8 Version)": ["Whirlwind", "Patient", "Penumbra Phantasm", "Doctor", "Showtime", "Crystalanthemums", "Crystamanthequins", "Spider's Claw", "Vriska's Theme"],
    "Wishful Thinking": ["Skies of Skaia", "Skaian Summoning", "Theme", "Rex Duodecim Angelus", "Penumbra Phantasm", "Upward Movement (Dave Owns)", "Lotus", "Homestuck Anthem", "Ruins", "Explore", "Skaian Skuffle", "Sburban Jungle", "Cascade (Beta)", "Overture (Canon Edit)", "Even in Death"],
    "\N{Dingbat Circled Sans-Serif Digit Eight}": ["Spider's Claw", "Vriska's Theme", "Rex Duodecim Angelus", "Amen, Brother"],
    "Blacker Than Licorice": ["Three in the Morning", "Liquid Negrocity", "Descend", "Umbral Ultimatum", "Walk-Stab-Walk", "Cascade (Beta)", "The Ballad of Jack Noir", "Lotus", "Non Compos Mentis", "Three's a Crowd", "Calamity", "Explore", "Flight of the White Wolf", "Amen, Brother", "Harlequin"],
    "Whirlwind": ["Showtime", "Doctor", "Patient", "Savior of the Waking World", "Penumbra Phantasm"],
    "Ignition": ["Flare (Cascade Cut)", "MeGaLoVania"],

    # ViKomprenas soundcloud
    "Another Elevator": ["Another Jungle", "Sburban Elevator"],
    "Elevator #3": ["Jungle #3", "Sburban Elevator"],
    "unfinished medley for power464646": ["Carbon Nadsat/Cuestick Genius", "Rhapsody in Green", "Havoc", "Eternity, Served Cold", "Showdown", "Riches to Ruins Movements I & II", "Negastrife", "PPiSHWA", "Carne Vale"],
    "Saiddit Lullaby": ["Colt Blooded", "Look Where We Are"],

    # UNDERTALE Soundtrack
    "Once Upon a Time": [],
    "Start Menu": ["Once Upon a Time"],
    "Your Best Friend": [],
    "Fallen Down": [],
    "Ruins (Undertale)": [],
    "Uwa!! So Temperate♫": [],
    "Anticipation (Undertale)": ["Enemy Approaching"],
    "Unnecessary Tension": [],
    "Enemy Approaching": [],
    "Ghost Fight": [],
    "Determination": [],
    "Home": ["Once Upon a Time"],
    "Home (Music Box)": ["Home"],
    "Heartache": ["Enemy Approaching"],
    "sans.": [],
    "Nyeh Heh Heh!": [],
    "Snowy": [],
    "Uwa!! So Holiday♫": ["Uwa!! So Temperate♫"],
    "Dogbass": ["Ghost Fight"],
    "Mysterious Place": [],
    "Dogsong": ["Enemy Approaching"],
    "Snowdin Town": ["Snowy"],
    "Shop": ["Snowy", "Snowdin Town"],
    "Bonetrousle": ["Nyeh Heh Heh!"],
    "Dating Start!": ["Snowdin Town"],
    "Dating Tense!": ["Undyne"],
    "Dating Fight!": ["Dating Start!"],
    "Premonition (Undertale)": ["You Idiot"],
    "Danger Mystery": [],
    "Undyne": [],
    "Waterfall": ["Ruins (Undertale)"],
    "Run!": ["Undyne"],
    "Quiet Water": ["Ruins (Undertale)"],
    "Memory": ["His Theme"],
    "Bird That Carries You Over a Disproportionately Small Gap": ["Alphys"],
    "Dummy!": ["Ghost Fight"],
    "Pathetic House": ["Ghost Fight"],
    "Spooktune": [],
    "Spookwave": ["Spooktune"],
    "Ghouliday": ["Jingle Bells"],
    "Chill": [],
    "Thundersnail": [],
    "Temmie Village": ["Dogsong"],
    "Tem Shop": ["Temmie Village"],
    "NGAHHH!!": ["Undyne", "Ruins (Undertale)"],
    "Spear of Justice": ["NGAHHH!!"],
    "Ooo": [],
    "Alphys": [],
    "It's Showtime!": [],
    "Metal Crusher": ["Noisemaster's Theme"],
    "Another Medium": ["Waterfall", "Patient"],
    "Uwa!! So HEATS!!♫": ["Uwa!! So Temperate♫"],
    "Stronger Monsters": ["Enemy Approaching"],
    "Hotel": ["Once Upon a Time"],
    "Can You Really Call This A Hotel, I Didn't Receive A Mint On My Pillow Or Anything": ["Hotel"],
    "Confession": ["Snowdin Town"],
    "Live Report": ["It's Showtime!"],
    "Death Report": ["Live Report"],
    "Spider Dance": ["Ghost Fight"],
    "Wrong Enemy ?!": [],
    "Oh! One True Love": [],
    "Oh! Dungeon": ["Oh! One True Love"],
    "It's Raining Somewhere Else": ["sans."],
    "CORE Approach": ["Hotel"],
    "CORE": ["Another Medium"],
    "Last Episode!": ["Metal Crusher"],
    "Oh My...": [],
    "Death by Glamour": ["Another Medium", "Metal Crusher", "It's Showtime!"],
    "For the Fans": ["Oh! One True Love"],
    "Long Elevator": [],
    "Undertale": ["His Theme", "Once Upon a Time"],
    "Song That Might Play When You Fight Sans": ["sans.", "Nyeh Heh Heh!"],
    "The Choice": ["Undertale"],
    "Small Shock": [],
    "Barrier": [],
    "Bergentrückung": ["Once Upon a Time"],
    "ASGORE": ["Bergentrückung", "Heartache", "Determination", "Undyne"],
    "You Idiot": [],
    "Your Best Nightmare": ["You Idiot", "Your Best Friend"],
    "Finale": ["Your Best Friend", "His Theme"],
    "An Ending": ["Ruins (Undertale)"],
    "She's Playing Piano": ["Alphys"],
    "Here We Are": ["Alphys"],
    "Amalgam": ["Enemy Approaching"],
    "Fallen Down (Reprise)": ["Fallen Down", "Once Upon a Time"],
    "Don't Give Up": ["An Ending"],
    "Hopes and Dreams": ["Once Upon a Time", "Your Best Friend", "Snowdin Town"],
    "Burn in Despair!": ["You Idiot"],
    "SAVE the World": ["Once Upon a Time", "Your Best Friend"],
    "His Theme": [],
    "Final Power": ["Hopes and Dreams"],
    "Reunited": ["Once Upon a Time", "Snowdin Town"],
    "Menu (Full)": ["Start Menu"],
    "Respite": ["Ruins (Undertale)"],
    "Bring It In, Guys!": ["Enemy Approaching", "Nyeh Heh Heh!", "sans.", "Snowy", "Snowdin Town", "Undyne", "Ruins (Undertale)", "Death by Glamour", "Another Medium", "Bergentrückung", "Fallen Down", "Once Upon a Time"],
    "Last Goodbye": ["Once Upon a Time"],
    "But the Earth Refused to Die": ["Ruins (Undertale)"],
    "Battle Against a True Hero": ["Ruins (Undertale)", "Alphys"],
    "Power of \"NEO\"": ["Battle Against a True Hero"],
    "MEGALOVANIA": ["Megalovania"],
    "Good Night": ["Once Upon a Time"],

    # UNDERTALE miscellany
    "Empty House": ["Fallen Down"],
    "Meat Factory": [],
    "Happy Town": [],
    "Trouble Dingle": [],
    "Gaster's Theme": [],
    "Grandpa Semi": ["Metal Crusher"],
    "King Description": ["Determination"],
    "Dance of Dog": [],
    "Sigh of Dog": [],
    "Alphys Lab (Unused)": ["Alphys"],
    "Undyne Battle (Unused)": ["Undyne", "Ruins (Undertale)"],
    "Dog Hole": [],
    "Dogtroid": ["Dogsong"],
    "Undertale (Beta)": ["Once Upon a Time"],

    # Misc
    "SPIDER DANCE FROM UNDERTALE BUT NOW ITS SKA I GUESS???": ["Spider Dance"],

    # Redditstuck Vol. 1
    "Cogs": [],
    "Hobbyist": [],
    "Spool": [],
    "Crushing Weight": [],
    "Assertion": [],
    "Visions of Grim": [],
    "Colt Blooded": ["Glass Houses"],
    "Incubation": [],
    "What A Hoot": [],
    "Saoshyant": ["Hobbyist"],
    "Alloy": [],
    "Conflict!": [],
    "Sticky Steps": [],
    "Happy Thoughts And Fairy Dust": [],
    "Effervescence": [],
    "Malediction": [],
    "Solid Water Whispers": [],
    "Divine Intervention": [],
    "Thank You Based Prince": [],
    "Look Where We Are": [],
    "Hyperion": [],

    # Redditstuck Vol. 2
    "Prelude For A Leading Lady": [],
    "Land of Glaciers and Magma": [],
    "Inflection": [],
    "Halcyon": ["My Favorite Things"],
    "Symmet": ["Symmet [Midi]"],
    "Symmet [Midi]": [],
    "In The Sorcerer's Tower": [],
    "Siphon": [],
    "Calmshit": [],
    "The Dremaer And The Dream": [],
    "Lewd Lunacy": [],
    "Slippery Slope": ["Sticky Steps"],
    "Gnade": [],
    "Calm Before Storm": [],
    "Glass Houses": [],
    "To Cross The Void": [],
    "Frieden": ["Ruhe"],
    "Where Are We Now": ["Look Where We Are"],
    "(I Can't Get No) Smooth Pencils": [],
    "Pizza Bagels": [],
    "The Fake-Out": [],
    "Maelstrom": [],

    # Hypertonic Dreams
    "Palfrey Motive": [],
    "Vitriolium": [],
    "Redox Redux": [],
    "All Saints to Arms": [],
    "Blueshift": [],
    "Den of Sin": [],
    "Duck Muffler": [],
    "Paperthin": ["Jingle Bell Rock"],
    "Reprieve": [],
    "Notes From The Left Field": [],
    "Hard Pill to Swallow": [],
    "Sad Mountain Dew Music": ["Sticky Steps"],
    "Tryptophantasm": [],
    "High Upon Hinterland": [],
    "Untruly Yours": [],
    "Burnout Flounce": [],
    "Ex Nihilo": [],

    # WarxTron soundcloud
    "Mannequin (WarxTron)": ["Mannequin"],
    "Solid Griscosity": ["Liquid Negrocity"],
    "Sunset (WarxTron)": ["Sunset (Toby Fox)"],
    "Last Breath of the Heir": ["Showtime (Piano Refrain)", "Doctor", "Penumbra Phantasm", "Harlequin", "Liquid Negrocity"],
    "Doctor Percocets": ["Doctor", "Mask Off", "Penumbra Phantasm"],
    "Patient (Full Mix)": ["Patient"],
    "Omnipotential Bark": ["Walk-Stab-Walk", "Sburban Jungle", "Atomic Bonsai", "Umbral Ultimatum", "Penumbra Phantasm", "Cascade", "Liquid Negrocity", "Dissension"],
    "Savior of the Hard Rock World": ["Savior of the Waking World"],
    "Waking Up": ["Penumbra Phantasm", "Doctor", "Get Up"],
    "8 BIT Liquid Negrocity": ["Liquid Negrocity"],
    "Breath Of Air": ["Doctor", "Penumbra Phantasm"],
    "Climbing for Eternity": ["Endless Climb"],
    "The Legend of the Sovereign Slayer": ["Liquid Negrocity", "The Ballad of Jack Noir"],
    "Strider Squadron": ["Upward Movement", "Beatdown", "Atomyk Ebonpyre", "Candles and Clockwork", "Unite Synchronization", "Sburban Jungle"],
    "It's Showtime (Homestuck Version)": ["Showtime", "It's Showtime"],
    "Doctor Lotus": ["Doctor", "Lotus"],
    "Legion of the Signless": ["Crustacean", "Chorale for Jaspers", "English"],
    "8-bit Keepers": ["Keepers"],
    "Calliope: Escape": [],
    "The Sun Is The Largest Star Setted In The Universe": ["Sunsetter", "Starsetter", "Sburban Jungle"],
    "Soft As The Clouds": ["Softly", "Softbit", "TBoSRE", "Sunsetter", "Penumbra Phantasm", "Dissension"],
    "Battle Against a Furry Dictator": ["Prospit Dreamers", "Furry Monarch"],

    # Phase
    "Epoch": ["Beatdown"],  # combined
    "Advanced Medical Action": ["Doctor"],
    "StarLight": [],
    "Edge Of Oblivion": ["At The Price of Oblivion"],
    "Strife In Sea Hitlers Palace": ["PPiSHWA"],  # sic
    "Awaken": ["MeGaLoVania", "Sburban Jungle", "Showtime"],
    "DeadTone": ["Dead Beat"],
    # Skipping Creatrix (duplicated w/ 9)
    "Final Fight": ["Doctor", "Even in Death", "Showtime", "MeGaLoVania", "PPiSHWA", "Beatdown"],

    # TirantBacon soundcloud
    "Non Compos Mentis Remix": ["Non Compos Mentis"],
    "Tomahawk Head - Shameful MIDI / soundfont swap edition": ["Tomahawk Head"],
    "Meganumbra Phantasm": ["Penumbra Phantasm", "Doctor"],
    "Crystalanthemix (WIP)": ["Crystalanthemums"],
    "earthlovania music dongers": ["Sunsetter", "MeGaLoVania", "Skies of Skaia"],
    "Jhons Rom (Old)": [],
    "I'm extremely sorry for this.": ["Walls Covered in Blood", "Soulja Boy"],
    "Admiral Bone-To-Pick (Wub Machine Remix)": ["Admiral Bone-To-Pick"],
    "Gaia King": ["Gaia Queen"],

    # Cerulean soundcloud
    "Life Support": ["Doctor"],
    "The Last Voyage": ["Eridan's Theme"],
    "Moonlight Slaughter": ["Liquid Negrocity"],

    # Redditstuck Vol. 3: Small Medium at Large
    # List compiled by Bin
    "Burnt Bridges": [],
    "Down Vice Street": [],
    "Down Lick Street": [],
    "Sparkle Fairy": [],
    "(That's) Inadvisable": [],
    "COblivion": [],
    "Clear Voyance": ["Gnade"],
    "Swing and a Miss": ["Pinkie's Brew"],
    "Attendre": [],
    "Bushito": [],
    "Smut Mania": [],
    "Pony Blooded": [],
    "Kotomundi": [],
    "Ypsilanti": [],
    "Hubris": [],
    "Robot": [],
    "sev": ["Kotomundi", "Hyperion", "Calmshit"],
    "Bygone": [],
    "Ruhe": [],
    "Coltish": [],
    "Unreal City": [],

    # Commander Cello soundcloud
    "Dead Dignitary": ["Liquid Negrocity"],

    # FriendlyCoy soundcloud
    "showtimejit.mp3": ["Joey: Play Haunting Refrain"],

    # Jit tumblr
    "Joey: Play Haunting Refrain": [],

    # GoldenSkylord soundcloud
    "FLburnward": ["Doctor"],

    # Dissectum/Rom/Doctor Chaos soundcloud
    "Seethe": ["Flare"],

    # Xoro Laventer soundcloud
    "Starcrusher": ["I absolutely LOATHE this Drummer."],

    # Act Omega - Early Access
    "Year One": ["Sburban Jungle", "Cascade (Beta)", "Umbral Ultimatum", "Penumbra Phantasm", "IaMotMC"],
    "Cog": ["Atomyk Ebonpyre", "Beatdown", "Cascade (Beta)"],
    "Blastoff": ["Sburban Jungle", "Cascade (Beta)", "Liquid Negrocity", "Aggrieve", "Penumbra Phantasm"],
    "Extermination": ["Extermination Alpha", "Sburban Jungle", "Cascade (Beta)"],
    "Queen Folly": ["Extermination Alpha"],
    "Wicked Witch": ["Extermination Alpha"],
    "Sburban Resolution": ["Sburban Jungle"],
    "Torrent (Bonus)": ["Sburban Jungle", "Cascade (Beta)", "Dance of Thorns", "Even in Death", "Upward Movement", "Love You", "Doctor"],
    "Savoir Allegro (Bonus)": ["Doctor"],
    "Extermination Alpha": [],
    "Meowlevatorstuck (Cat Tax)": ["Elevatorstuck"],
}


def parse():
    return [Track(x, y) for x, y in nsnd.items() if y is not NotImplementedError]
